// Code generated by "stringer -type=ServerState"; DO NOT EDIT.

package ultraviolet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Online-1]
	_ = x[Offline-2]
}

const _ServerState_name = "UnknownOnlineOffline"

var _ServerState_index = [...]uint8{0, 7, 13, 20}

func (i ServerState) String() string {
	if i >= ServerState(len(_ServerState_index)-1) {
		return "ServerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerState_name[_ServerState_index[i]:_ServerState_index[i+1]]
}
