// Code generated by "stringer -type=HandshakeState"; DO NOT EDIT.

package mc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownState-0]
	_ = x[Status-1]
	_ = x[Login-2]
}

const _HandshakeState_name = "UnknownStateStatusLogin"

var _HandshakeState_index = [...]uint8{0, 12, 18, 23}

func (i HandshakeState) String() string {
	if i >= HandshakeState(len(_HandshakeState_index)-1) {
		return "HandshakeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HandshakeState_name[_HandshakeState_index[i]:_HandshakeState_index[i+1]]
}
