{
 "title": "Ultraviolet",
 "tags": [ "prometheus" ],
 "time": { "from": "2021-08-12T09:56:31.769Z", "to": "2021-08-12T10:42:47.187Z" },
 "panels": [
  {
   "title": "Requests by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ultraviolet_request_duration_seconds_count[1m])) by (type)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests per server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(server)(irate(ultraviolet_request_duration_seconds_count[1m]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Requests processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ultraviolet_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Avg process time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ultraviolet_request_duration_seconds_sum) by (le) / sum(ultraviolet_request_duration_seconds_count) by (le)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ultraviolet_player_connected)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "player-instance distribution",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(ultraviolet_player_connected)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(ultraviolet_player_connected)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ultraviolet_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}