// Code generated by "stringer -type=BackendAction"; DO NOT EDIT.

package worker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Proxy-1]
	_ = x[Disconnect-2]
	_ = x[SendStatus-3]
	_ = x[Close-4]
}

const _BackendAction_name = "ErrorProxyDisconnectSendStatusClose"

var _BackendAction_index = [...]uint8{0, 5, 10, 20, 30, 35}

func (i BackendAction) String() string {
	if i >= BackendAction(len(_BackendAction_index)-1) {
		return "BackendAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BackendAction_name[_BackendAction_index[i]:_BackendAction_index[i+1]]
}
