// Code generated by "stringer -type=ProxyAction"; DO NOT EDIT.

package worker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProxyOpen-0]
	_ = x[ProxyClose-1]
}

const _ProxyAction_name = "ProxyOpenProxyClose"

var _ProxyAction_index = [...]uint8{0, 9, 19}

func (i ProxyAction) String() string {
	if i < 0 || i >= ProxyAction(len(_ProxyAction_index)-1) {
		return "ProxyAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProxyAction_name[_ProxyAction_index[i]:_ProxyAction_index[i+1]]
}
